"""initial schema

Revision ID: 2fac6eebf450
Revises: 
Create Date: 2025-12-18 21:59:28.973106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fac6eebf450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_table('practice_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_templates_id'), 'practice_templates', ['id'], unique=False)
    op.create_table('practice_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('warmup', sa.Text(), nullable=True),
    sa.Column('scales', sa.Text(), nullable=True),
    sa.Column('repertoire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['practice_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_days_id'), 'practice_days', ['id'], unique=False)
    op.create_table('practice_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['practice_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_logs_id'), 'practice_logs', ['id'], unique=False)
    op.create_table('exercise_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_day_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_day_id'], ['practice_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_blocks_id'), 'exercise_blocks', ['id'], unique=False)
    op.create_table('practice_log_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['practice_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_log_details_id'), 'practice_log_details', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('exercise_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['exercise_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_practice_log_details_id'), table_name='practice_log_details')
    op.drop_table('practice_log_details')
    op.drop_index(op.f('ix_exercise_blocks_id'), table_name='exercise_blocks')
    op.drop_table('exercise_blocks')
    op.drop_index(op.f('ix_practice_logs_id'), table_name='practice_logs')
    op.drop_table('practice_logs')
    op.drop_index(op.f('ix_practice_days_id'), table_name='practice_days')
    op.drop_table('practice_days')
    op.drop_index(op.f('ix_practice_templates_id'), table_name='practice_templates')
    op.drop_table('practice_templates')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###


