"""add_users_and_system_templates

Revision ID: 5f1f5320f901
Revises: 743b48d944ba
Create Date: 2026-01-07 12:02:07.703831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5f1f5320f901'
down_revision = '743b48d944ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    
    # 2. Add columns to instruments table with default values
    op.add_column('instruments', sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('instruments', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 3. Mark all existing instruments as system instruments (data migration)
    op.execute("UPDATE instruments SET is_system = true WHERE user_id IS NULL")
    
    # 4. Update instruments indexes and foreign keys
    op.drop_index('ix_instruments_name', table_name='instruments')
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=False)
    op.create_foreign_key(None, 'instruments', 'users', ['user_id'], ['id'])
    
    # 5. Add columns to practice_templates table with default values
    op.add_column('practice_templates', sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('practice_templates', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 6. Mark all existing templates as system templates (data migration)
    op.execute("UPDATE practice_templates SET is_system = true WHERE user_id IS NULL")
    
    # 7. Add foreign key for practice_templates
    op.create_foreign_key(None, 'practice_templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_templates', type_='foreignkey')
    op.drop_column('practice_templates', 'user_id')
    op.drop_column('practice_templates', 'is_system')
    op.drop_constraint(None, 'instruments', type_='foreignkey')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.create_index('ix_instruments_name', 'instruments', ['name'], unique=True)
    op.drop_column('instruments', 'user_id')
    op.drop_column('instruments', 'is_system')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


