"""Add user_id to practice_logs

Revision ID: 6112e8733982
Revises: 0bba8a5dc1ec
Create Date: 2026-01-27 14:17:33.905585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6112e8733982'
down_revision = '0bba8a5dc1ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_practice_logs_user_id'), 'practice_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'practice_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_logs', type_='foreignkey')
    op.drop_index(op.f('ix_practice_logs_user_id'), table_name='practice_logs')
    op.drop_column('practice_logs', 'user_id')
    # ### end Alembic commands ###


