"""add_updated_at_and_deleted_at_columns

Revision ID: f0612b1838c1
Revises: 5f1f5320f901
Create Date: 2026-01-21 14:09:35.699951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0612b1838c1'
down_revision = '5f1f5320f901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_blocks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('exercises', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('practice_days', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('practice_log_details', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('practice_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('practice_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Add created_at as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('practice_templates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE practice_templates SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('practice_templates', 'created_at', nullable=False)
    
    op.add_column('practice_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('practice_templates', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('practice_templates', 'deleted_at')
    op.drop_column('practice_templates', 'updated_at')
    op.drop_column('practice_templates', 'created_at')
    op.drop_column('practice_logs', 'deleted_at')
    op.drop_column('practice_logs', 'updated_at')
    op.drop_column('practice_log_details', 'updated_at')
    op.drop_column('practice_days', 'updated_at')
    op.drop_column('exercises', 'updated_at')
    op.drop_column('exercise_blocks', 'updated_at')
    # ### end Alembic commands ###


