"""Make template_id and day_number nullable on practice_logs

Revision ID: 0bba8a5dc1ec
Revises: a1b2c3d4e5f6
Create Date: 2026-01-27 14:01:23.105649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bba8a5dc1ec'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_logs', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('practice_logs', 'day_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_logs', 'day_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('practice_logs', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


